appender=com.p6spy.engine.spy.appender.StdoutLogger
logMessageFormat=com.p6spy.engine.spy.appender.CustomLineFormat

customLogMessageFormat=\n================ SQL LOG ================\nTime: %(currentTime)\nExecution: %(executionTime) ms\n\n%(sql)\n\n=========================================

excludecategories=info,debug,result,resultset,batch